### ISSUE TITLE
Сбрасывается utf8 флаг при парсинге

### ISSUE THREAD

**Issue by asan13** [Litres/TurboXSLT#3]
Привет!
Похоже, что где-то в XS сбрасывается utf8 флаг. В callback попадает строка со сброшенным флагом, хотя изначально строка декодированная, с флагом. Хотя возможно, проблема в самом turboxsl. Тесткейз прилагаю. 

```
#!/usr/bin/perl
use strict;
use warnings;
use utf8;

use TurboXSLT;

my $str = 'Хелло, ворлд!';

my $xslt = TurboXSLT->new();

$xslt->RegisterCallback( 'ltr:test_utf8', sub {
     print "=== @_ >>> is_utf8: ", utf8::is_utf8($_[0]), "\n";
     utf8::decode $_[0];
     $_[0];
});

my $doc = $xslt->Parse(  qq!<broken xxx="$str"/>! );

my $style = $xslt->LoadStylesheet('./broken.xml');
my $res   = $style->Transform($doc);
#print $style->Output($res);
```

xslt:

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet 
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:ltr="LTR"
   version="1.0"
>
  <xsl:template match="/">
    <xsl:value-of select="ltr:test_utf8(ltr:test_utf8(@xxx))"/>
  </xsl:template>
</xsl:stylesheet>
```

Вывод:

```
=== Хелло, ворлд! >>> is_utf8: 
=== Хелло, ворлд! >>> is_utf8:
```

[testturbo.zip](https://github.com/Litres/TurboXSLT/files/239356/testturbo.zip)

_Андрей Асякин, Литрес_
_skype: andrey_asyakin_

**Comment by asan13** [comment]
Черт, я ж забыл, что там по сокетам передаются данные.. значит, я сморозил, багрепорт отменяется)

**Comment by dijer** [comment]
ok =) Если что у меня скайп dijerus ты у меня в фл


>Четверг, 28 апреля 2016, 10:45 +03:00 от Андрей Асякин <notifications@github.com>:
>
>Черт, я ж забыл, что там по сокетам передаются данные.. значит, я сморозил, багрепорт отменяется)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Ахметзянов Тимур
